# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi
# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
typeset -g POWERLEVEL9K_INSTANT_PROMPT=quiet # 当主题加载时保持安静，不显示警告信息 

source ~/.zsh/plugins/powerlevel10k/powerlevel10k.zsh-theme

# ---- zsh-completions ----
fpath=(~/.zsh/plugins/zsh-completions/src $fpath)

# ---- zsh-autosuggestions ----
HISTFILE=~/.zsh_history
HISTSIZE=10000
SAVEHIST=10000
setopt hist_ignore_dups       # 忽略重复命令
setopt hist_ignore_all_dups   # 忽略所有重复历史
setopt hist_ignore_space      # 开头带空格的命令不保存
setopt hist_reduce_blanks     # 自动去掉多余空格
setopt append_history
setopt inc_append_history
setopt share_history
source ~/.zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh

# ---- zsh-syntax-highlighting ----
source ~/.zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

# local index
source ~/.zsh/local_index.sh

# bind keys
bindkey '^z' autosuggest-execute

export EDITOR=nvim
